### ISSUE TITLE
Проверь тесты

### ISSUE THREAD

**Issue by Sergey111991KV** [pf03/server#4]
Скорее всего ты делал переименования, а про тесты забыл - проверь их) а import Interface.Error as Error () - в принципе вообще не имеет значения)

**Comment by pf03** [comment]
Подправил. По опыту бота знаю, что тесты придется переделывать многократно, поэтому оставляю их на последний момент

**Comment by Sergey111991KV** [comment]
ну это да) но лучше их править постоянно, чтобы не отрываться от проекта - когда будет много правок будет труднее их править. А еще лучше за правило возьми  всегда их править, если проект будет вертеться в CI, то там может быть условие запуска тестов после каждого комита. И если тесты не проходят - то соответственно ничего не работает
