### ISSUE TITLE
Убрать ненужные комментарии

### ISSUE THREAD

**Issue by KateBushueva** [pf03/server#6]
Убрать технические комментарии - типа закомменченные ненужные функции/импорты/имплементации и т.п.

**Comment by pf03** [comment]
Можешь привести примеры? Я в сервере не нашел закомментированный код. Может у тебя устаревший репозиторий? Или имеются в виду просто неиспользуемые функции, а не закомментированные? Такие конечно есть, но я не считаю это ошибкой. Мы же например не обязаны использовать все функции, которые прописаны в библиотеке.

**Comment by KateBushueva** [comment]
ну, например, в `Main.hs` : 
```
main :: IO()
main = App.main_
-- main = error "Not implemented main function yet"
```

**Comment by KateBushueva** [comment]
Если ты пишешь библиотеку - то ты, безусловно, пишешь функции, которые могут пригодиться пользователям, не важно какая часть из них будет использоваться в конкретном случае. 
Однако в проекте оставлять неиспользуемые функции - это зло, проект засоряется такими вещами очень быстро, особенно когда над ним работает несколько человек. Если нет юзкейса, не должно быть и функции. Если появляется юзкейс - пишется функция (или восстанавливается из гита, если она уже была когда-то написана - но обычно проще заново написать).

**Comment by KateBushueva** [comment]
в общем, надо удалить и закоменченный код и неиспользуемый код тоже

**Comment by pf03** [comment]
> Если ты пишешь библиотеку - то ты, безусловно, пишешь функции, которые могут пригодиться пользователям, не важно какая часть из них будет использоваться в конкретном случае.
> Однако в проекте оставлять неиспользуемые функции - это зло

Приведу пример. В тестах у меня есть модуль Lib, мини библиотека для разных хитрых случаев тестирования ( в монаде State, тестирование для списка и т д.) После чего я тесты много раз переделывал (упрощал) и большая часть оказалась не нужна, хотя эти функции вполне логичны и прекрасно работают. Это все удалять?

**Comment by KateBushueva** [comment]
да, все эти функции все равно останутся в истории гита и ты в любой момент можешь их восстановить. Но в текущей реализации они не нужны

**Comment by pf03** [comment]
Или еще пример, отладочные функции типа Color.сolorTable, они нигде в коде не используются, но при разработке можно использовать, в данном случае для выбора читаемых цветов лога. И такое удалять?

**Comment by KateBushueva** [comment]
такое можно оставлять

**Comment by pf03** [comment]
> да, все эти функции все равно останутся в истории гита и ты в любой момент можешь их восстановить. Но в текущей реализации они не нужны

Удалил неиспользуемые функции, хоть и не думаю, что это правильно. Часто удаленные функции логически дополняют существующие
