### ISSUE TITLE
наименования

### ISSUE THREAD

**Issue by KateBushueva** [pf03/server#7]
Вот еще по поводу имен: есть кусок кода (`Logic.DB.Migrations.Internal`)

```
    -- Check format 0000_migration_name.sql
    helper :: FileName -> Bool
    helper (a : b : c : d : '_' : xs) | all (`elem` show [0 :: Int .. 9]) [a, b, c, d] && ".sql" `isSuffixOf` xs = True
    helper _ = False
```
если ты вместо helper назовешь функцию checkFormat, то необходимости в комментировании не будет. 
Проверь такие вещи в коде

**Comment by pf03** [comment]
исправил, где нашел
